### ISSUE TITLE
driver dump

### ISSUE THREAD

**Issue by seikichin** [sirdude/gurbalib#21]
I use gurbalib and the driver dump :
driver->binary_connect() did not return persistent object 5 [main] dgd 343 cygwin_exception::open_stackdumpfile: Dumping stack trace to dgd.exe.stackdump C:\Users\Admini
I config local_config. h disable the ftp
like this:
define DISABLE_FTP 1 */
if anyone try to connect the 4001 port the driver will dump

**Comment by sirdude** [comment]
I believe this is more a dgd issue than a gurbalib issue, I see that you posted in the dgd issue tracker as well, I'm going to wait and see if it doesn't get addressed there.

**Comment by seikichin** [comment]
one problem the afun remove_file:
static int remove_file(string file) {
   if (!valid(file, MODE_WRITE)) {
#ifdef ENABLE_STACK_SECURITY
      console_msg("Access to " + file + " denied\n");
      return 0;
#else
      console_msg("Access to " + file +
         " would have been denied, ignoring...\n");
#endif
   }
 
   return::remove_file(file);
}
should not be static

**Comment by november-kilo** [comment]
Your driver dump error is hard to understand without knowing what version of DGD you're using and your gurbalib code. I recall that at some point last autumn, networking functions were removed for some reason, but I don't know if that's causing the problem.

As far as I know, all the afuns should be static. I don't know why some are and some are not. What is your use case that this one should not be static?

**Comment by seikichin** [comment]
gurbalib 0.5 dgd 1.6.7

**Comment by november-kilo** [comment]
In a fresh repository for gurbalib and DGD, I disabled FTP and get the following
```
$ telnet localhost 4001
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
Do you have a repository you can share?

**Comment by seikichin** [comment]
if remove_file is static the rmuser cmd can not be used
 
---Original---

**Comment by november-kilo** [comment]
If we have DISABLE_FTP defined, then we need to provide a `connection()` function for the driver. I used the following to address crash on connecting to port 4001
```c
#ifndef DISABLE_FTP
void initialize(void) {
   open_port("tcp", FTP_PORT);
}

object connection(string ip, int port) {
   object con, session;

   session = clone_object("/sys/daemons/ftp_session");
   con = clone_object("/kernel/obj/net/connection");
   session->set_connection(con);
   return (con);
}

void create(void) {
   initialize();
}
#else
object connection(string ip, int port) {
    error("Disabled.");
}
#endif
```

I looked at rmuser and it appears you're correct that it shouldn't be static.

I'll see about making a pull request later.

**Comment by seikichin** [comment]
ok thanks


 
---Original---
