### ISSUE TITLE
document here style string

### ISSUE THREAD

**Issue by seikichin** [sirdude/gurbalib#22]
In dead-souls mudlib I can SetLong(@EndText
|---------------------------------------------------------------|-------------|
This is an example room for inheriting files.  This 
file is inherited by two others.  It's also a fully
functional room.  There's a lever to pull.
The rooms which inherit me are to the east.
EndText
    );

    //  You'll notice that for SetLong(), I've put @EndText at the top and EndText at the bottom
    //    and have not put in quotes. can I use this style of code in gurbalib,

**Comment by november-kilo** [comment]
No. In gurbalib, the user determines the screen width with the `set width <number>` command. Before strings get displayed to the user, they are broken up according to that setting. It also provides a `\n` at the end of the string. So, you only need to write
```c
set_long("This is an example room for inheriting files. This " +
    "file is inherited by two others. It's also a fully " +
    "functional room. There's a lever to pull. " +
    "The rooms which inherit me are to the east.");
```

**Comment by seikichin** [comment]
get it. thank you for your help
