### ISSUE TITLE
query_followers fails if no followers

### ISSUE THREAD

**Issue by jandrieu** [sirdude/gurbalib#43]
in std/body/follow.c, the query_followers function fails if "followers" is not initialized.

I hacked a quick work around by calling clear_followers, but it seems like that should be in an initialization function. 

I considered adding it to body.c, but I wasn't sure if that would be the right way to do it.

**Comment by sirdude** [comment]
I added a call to clear_followers might rename it eventually to something else but for now that works.

Thanks for the note.
