### ISSUE TITLE
Double body_enter events being fired

### ISSUE THREAD

**Issue by Dave-Driesen** [sirdude/gurbalib#6]
Thanks for your great work!

I've noticed that the body_enter event gets fired twice whenever an object enters a room..

Stack traces show that this is caused by both the room, and the object, firing the body_enter event. Specifically:

- room.c, in function body_exit(), calling: room->event("body_enter", who);
- object.c, in function move(), calling: dest->event("body_enter", this_object());

This seems to be a bug; if not then it certainly complicates things for the called function. It becomes hard (impossible?) to discriminate between callers.

**Comment by november-kilo** [comment]
Seems to me that
```
   if (this_object()->is_living()) {
      dest->event("body_enter", this_object());
   }
```
can be removed from `object.c`

**Comment by Dave-Driesen** [comment]
Thanks, that was my fix also and seems to work great for now.

It seems more appropriate for the event code to branch on is_living() if required anyway.

Thanks again for your great and valuable work on this.

**Comment by sirdude** [comment]
Sorry it took me so long to respond to this been really busy at work.  I've committed the change.
